# This is the Docker Compose entry point for this project.
# Services listed in this file will automatically be built and started when you bring
# the project up.
version: "3.7"
services:
  nginx-starter:
    image: nginx:alpine
    ports:
      - 8080:80
    depends_on:
      - elgg-starter
    volumes:
      - ./services/nginx-starter/default.conf:/etc/nginx/conf.d/default.conf:ro,cached
      - ./services/elgg-starter/web:/var/www/html/web:cached
  elgg-starter:
    build:
      context: ./services/elgg-starter
    depends_on:
      - mysql
    command:
      - sh
      - -c
      - >-
        chmod -R 0777 /var/data/elgg-data

        composer install --ignore-platform-reqs

        exec php-fpm
    environment:
      MYSQL_DATABASE: web
      MYSQL_USER: web
      MYSQL_PASSWORD: web
      MYSQL_HOST: mysql
      WAIT_HOSTS: mysql:3306
      WAIT_PATHS: /var/www/html/vendor/autoload.php
      WAIT_SLEEP_INTERVAL: 3
      ELGG_WWWROOT: http://localhost:8080/
      ELGG_DATAROOT: /var/data/elgg-data/
      ELGG_DB_PREFIX: elgg_starter_
      ELGG_ADMIN_USER: admin
      ELGG_ADMIN_EMAIL: admin@example.com
      ELGG_ADMIN_PASSWORD: Adm1npwd
    volumes:
      - ./services/elgg-starter:/var/www/html:cached
      - type: volume
        source: fs-data-starter
        target: /var/data/elgg-data
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: web
      MYSQL_USER: web
      MYSQL_PASSWORD: web
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    ports:
      - 13306:3306
    volumes:
      - type: volume
        source: mysql-data
        target: /var/lib/mysql
  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
volumes:
  ? fs-data-starter
  ? mysql-data
